name: Rust
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["*"]
jobs:
  stable:
    runs-on: ubuntu-latest
    steps:
    - name: Install Rust stable.
      run: rustup install stable
    - uses: actions/checkout@v1
    - name: Build
      run: cargo +stable build --verbose
    - name: Run tests
      run: cargo +stable test --verbose
  nightly:
    runs-on: ubuntu-latest
    steps:
    - name: Install Rust nightly.
      run: rustup install nightly
    - uses: actions/checkout@v1
    - name: Build
      run: cargo +nightly build --verbose
    - name: Run tests
      run: cargo +nightly test --verbose
