name: Rust
on:
  push:
    branches: ["master"],
  pull_request:
    branches: ["*"],

jobs:
  nightly:
    runs-on: ubuntu-latest
    steps:
    - name: Install Rust nightly.
      run: rustup install nightly
    - uses: actions/checkout@v1
    - name: Build
      run: cargo +nightly build --verbose
    - name: Run tests
      run: cargo +nightly test --verbose
